Install content shell also

diff --git a/scripts/dvm b/scripts/dvm
--- a/scripts/dvm
+++ b/scripts/dvm
@@ -199,7 +199,20 @@ _dvm_download_sdk() {
 
   local dl_uri="https://storage.googleapis.com/dart-archive/channels/$channel/release"
   local base_uri="$dl_uri/$version"
+  echo "Downloading: $base_uri/sdk/$sdk_archive"
   curl -f -O "$base_uri/sdk/$sdk_archive"
+}
+
+_dvm_download_content_shell() {
+  local channel=$1
+  local version=$2
+  local content_shell_archive=$3
+
+  local dl_uri="https://storage.googleapis.com/dart-archive/channels/$channel/release"
+  local base_uri="$dl_uri/$version"
+  echo "Downloading: $base_uri/dartium/$content_shell_archive"
+  curl -f -O "$base_uri/dartium/$content_shell_archive"
+
 }
 
 _dvm_download_dartium() {
@@ -209,6 +222,7 @@ _dvm_download_dartium() {
 
   local dl_uri="https://storage.googleapis.com/dart-archive/channels/$channel/release"
   local base_uri="$dl_uri/$version"
+  echo "Downloading: $base_uri/dartium/$dartium_archive"
   curl -f -O "$base_uri/dartium/$dartium_archive"
 }
 
@@ -235,10 +249,12 @@ dvm_install() {
   case $(uname) in
     Darwin)
       local sdk_archive=dartsdk-macos-x64-release.zip
+      local content_shell_archive=content_shell-macos-ia32-release.zip
       local dartium_archive=dartium-macos-ia32-release.zip
       ;;
     Linux)
       local sdk_archive=dartsdk-linux-x64-release.zip
+      local content_shell_archive=content_shell-linux-ia32-release.zip
       local dartium_archive=dartium-linux-x64-release.zip
       ;;
     *)
@@ -269,6 +285,34 @@ dvm_install() {
     rm -rf -- "$DVM_ROOT/darts/$version"
   fi
   mv dart-sdk "$DVM_ROOT/darts/$version"
+
+  # Download Content Shell
+  for channel in "stable" "dev"; do
+    _dvm_download_content_shell "$channel" "$version" "$content_shell_archive" && break
+  done
+  if [[ $? -ne 0 ]]; then
+    echo "ERROR: unable to download Content Shell. But hey, at least you got the SDK."
+  else
+    unzip $content_shell_archive
+    if [[ ! -d "$DVM_ROOT/darts/$version/content_shell" ]]; then
+      local content_shell_dir="$(find . -maxdepth 1 ! -path . -type d)"
+      mv "$content_shell_dir" "$DVM_ROOT/darts/$version/content_shell"
+    fi
+
+    # Create Content Shell symlink.
+    pushd "$DVM_ROOT/darts/$version/bin" > /dev/null
+    case $(uname) in
+      Darwin)
+        echo "#!/bin/bash" > content_shell
+        echo "exec \"$DVM_ROOT/darts/$version/content_shell/Content Shell.app/Contents/MacOS/Content Shell\" \"\$@\"" >> content_shell
+        chmod ugo+x content_shell
+        ;;
+      Linux)
+        ln -s ../content_shell/content_shell content_shell
+        ;;
+    esac
+    popd > /dev/null
+  fi
 
   # Download Dartium.
   for channel in "stable" "dev"; do
